"""Single-page local dashboard for a read-only-data, virtual paper account.

The browser never receives Upstox credentials.  It communicates only with the
local dashboard server, whose paper endpoints can create virtual ledger entries
but contain no Upstox order API calls.
"""

from __future__ import annotations


def render_paper_trading_page() -> bytes:
    """Render the paper dashboard shell; JavaScript fills it from local APIs."""
    return _HTML.encode("utf-8")


_HTML = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Quant India — Local Paper Trading</title>
<style>
:root { --bg:#0b1120; --panel:#111b2e; --edge:#263a58; --text:#e9f1ff; --muted:#91a5c3; --green:#46d99b; --amber:#ffd166; --red:#fb7185; --blue:#6ea8fe; }
* { box-sizing:border-box } body { margin:0; background:var(--bg); color:var(--text); font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
main { max-width:1420px; padding:24px; margin:auto } header { display:flex; gap:16px; align-items:flex-start; justify-content:space-between; border-bottom:1px solid var(--edge); padding-bottom:18px; margin-bottom:20px; } h1{font-size:1.5rem;margin:0 0 5px} h2{font-size:1rem;margin:0 0 13px} p{margin:0}.subtitle,.small{color:var(--muted);font-size:.88rem}.tag{font-size:.72rem;font-weight:750;letter-spacing:.06em;padding:4px 8px;border-radius:99px;border:1px solid var(--edge);color:var(--blue);white-space:nowrap}.paper{color:var(--green);border-color:#1f7455;background:#123b2e}.warn{color:var(--amber);border-color:#765d1b;background:#3a2e10}.bad{color:var(--red);border-color:#793142;background:#3d1925}
.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.two{display:grid;grid-template-columns:1.2fr .8fr;gap:14px;margin-top:14px}.card{background:var(--panel);border:1px solid var(--edge);border-radius:12px;padding:16px}.metric .label{text-transform:uppercase;color:var(--muted);font-size:.70rem;letter-spacing:.06em}.metric .value{font-size:1.35rem;font-weight:700;margin-top:5px}.pos{color:var(--green)}.neg{color:var(--red)}
.banner{padding:12px 14px;border:1px solid #1f7455;background:#102e25;border-radius:9px;margin:0 0 14px;font-size:.87rem}.banner strong{color:var(--green)}.notice{padding:11px 14px;border-radius:9px;margin:14px 0;background:#392d12;border:1px solid #6f5a1c;color:#ffe29a;font-size:.88rem}
.controls{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.controls label{font-size:.78rem;color:var(--muted)} input,select{background:#0a1425;color:var(--text);border:1px solid var(--edge);padding:8px;border-radius:7px}button{color:#fff;background:#2457a6;border:1px solid #3d77cf;padding:8px 11px;border-radius:7px;cursor:pointer;font-weight:650}button:hover{filter:brightness(1.12)}button.danger{background:#721d35;border-color:#a83554}button.secondary{background:#17263d;border-color:#334f74}button:disabled{opacity:.5;cursor:not-allowed}
table{border-collapse:collapse;width:100%;font-size:.84rem}th{color:var(--muted);font-size:.71rem;text-align:left;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid var(--edge);padding:8px 7px}td{padding:9px 7px;border-bottom:1px solid #1a2b45}td.num,th.num{text-align:right;font-variant-numeric:tabular-nums}.scroll{overflow:auto;max-height:360px}.strategy{border:1px solid var(--edge);border-radius:8px;padding:10px;margin:7px 0;display:flex;justify-content:space-between;gap:10px}.strategy strong{font-size:.9rem}.strategy .small{margin-top:3px}.statusline{font-size:.85rem;color:var(--muted);min-height:18px;margin-top:9px}.modal{position:fixed;inset:0;background:#000a;display:none;align-items:center;justify-content:center;padding:20px}.modal.open{display:flex}.dialog{max-width:600px;width:100%;background:var(--panel);border:1px solid var(--edge);border-radius:12px;padding:20px}.dialog h2{font-size:1.15rem}.dialog pre{white-space:pre-wrap;max-height:260px;overflow:auto;padding:12px;background:#0a1425;border:1px solid var(--edge);border-radius:7px;font-size:.77rem}.dialog .controls{margin-top:14px}
@media(max-width:950px){.grid{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}}@media(max-width:550px){main{padding:14px}.grid{grid-template-columns:1fr}header{display:block}.tag{display:inline-block;margin-top:10px}}
</style></head><body><main>
<header><div><h1>Local Paper Trading</h1><p class="subtitle">Live Upstox <b>market data</b> + a separate, virtual INR portfolio. Nothing on this page can place a real order. <a href="/cockpit">Research Cockpit</a> · <a href="/strategy">Strategy dashboard</a></p></div><div class="tag paper">PAPER ONLY · READ-ONLY DATA</div></header>
<div class="banner"><strong>Safety boundary:</strong> virtual cash, positions, orders and P&amp;L are stored only in the local <code>var/paper_trading.sqlite</code> ledger. The Upstox integration is quote-only; it has no order, funds, holdings or GTT calls.</div>
<div id="message"></div>
<section class="grid" id="metrics"><div class="card metric"><div class="label">Virtual equity</div><div class="value">—</div></div></section>
<section class="two"><div class="card"><h2>Paper account controls</h2><div class="controls"><label>Virtual capital ₹<input id="capital" type="number" min="1" step="1000" value="1000000"></label><label>Data source <select id="data-mode"><option value="UPSTOX_DATA">Upstox data only</option><option value="SANDBOX">Upstox Sandbox</option></select></label><button onclick="configureAccount()">Save configuration</button><button class="secondary" onclick="startMonitor()">Start monitor</button><button class="secondary" onclick="pauseMonitor()">Pause</button><button onclick="refreshQuotes()">Refresh now</button><button class="danger" onclick="resetPaper()">Reset paper account</button></div><p class="statusline" id="connection">Loading connection status…</p><div class="notice"><b>Setup required for live quotes:</b> an Upstox <code>access token</code> is needed in the local environment. Your API key/secret stays private and is used only in the broker OAuth flow—never pasted into this dashboard.</div></div>
<div class="card"><h2>Paper strategy gate</h2><div id="strategies">Loading strategy registry…</div><p class="small">A strategy arrives here only after we implement it, backtest it with costs/OOS checks, and mark it paper-approved in the audited registry. This UI does not execute arbitrary code pasted into a browser.</p></div></section>
<section class="two"><div class="card"><h2>Watchlist &amp; risk guardrails</h2><p class="small">Comma-separated, verified NSE/benchmark symbols. Rebalance previews are blocked before virtual fills if a guardrail fails.</p><div class="controls" style="margin-top:10px"><label>Watchlist <input id="watchlist-input" size="38" aria-label="Watchlist symbols"></label><button class="secondary" onclick="saveWatchlist()">Save watchlist</button></div><div class="controls" style="margin-top:10px"><label>Max position % <input id="risk-position" type="number" min="1" max="100" step="1"></label><label>Max gross % <input id="risk-gross" type="number" min="1" max="100" step="1"></label><label>Daily loss % <input id="risk-daily-loss" type="number" min="1" max="100" step="1"></label><label>Max drawdown % <input id="risk-drawdown" type="number" min="1" max="100" step="1"></label><label>Max orders <input id="risk-orders" type="number" min="1" max="100" step="1"></label><button class="secondary" onclick="saveRiskPolicy()">Save guardrails</button></div><p class="statusline" id="risk-status">Loading risk status…</p></div>
<div class="card"><h2>Local ledger tools</h2><div class="controls"><button class="secondary" onclick="runAudit()">Run reconciliation audit</button><a class="tag" href="/api/paper/export?dataset=orders">Orders CSV</a><a class="tag" href="/api/paper/export?dataset=positions">Positions CSV</a><a class="tag" href="/api/paper/export?dataset=equity">Equity CSV</a><a class="tag" href="/api/paper/export?dataset=marks">Marks CSV</a></div><p class="statusline" id="audit-status">Audit not run in this browser session.</p><h2 style="margin-top:20px">Optional auto paper mode</h2><div class="controls"><label>Approved strategy <select id="auto-strategy"></select></label><button class="secondary" onclick="setAutomation(true)">Enable auto paper</button><button class="secondary" onclick="setAutomation(false)">Disable</button></div><p class="small" id="automation-status">Disabled by default. Enabling requires the exact confirmation and can only select an approved strategy. It writes virtual fills only during NSE hours and remains risk-gated.</p></div></section>
<section class="two"><div class="card"><h2>Current virtual positions &amp; live P&amp;L</h2><div class="scroll"><table><thead><tr><th>Symbol</th><th class="num">Qty</th><th class="num">Entry ₹</th><th class="num">Last ₹</th><th class="num">Value ₹</th><th class="num">Unrealised ₹</th><th>Quote time</th></tr></thead><tbody id="positions"><tr><td colspan="7" class="small">No virtual positions.</td></tr></tbody></table></div></div>
<div class="card"><h2>Live watchlist / intraday quote tape</h2><p class="small">Polls the data API every 30 seconds while this tab is open. Each snapshot is saved locally, which begins building an intraday research record.</p><div class="scroll"><table><thead><tr><th>Instrument</th><th class="num">LTP ₹</th><th class="num">Bid ₹</th><th class="num">Ask ₹</th><th class="num">Volume</th><th>Time</th></tr></thead><tbody id="watchlist"><tr><td colspan="6" class="small">No quote snapshot yet.</td></tr></tbody></table></div></div></section>
<section class="two"><div class="card"><h2>Virtual order ledger</h2><div class="scroll"><table><thead><tr><th>Time</th><th>Strategy</th><th>Symbol</th><th>Side</th><th class="num">Qty</th><th class="num">Fill ₹</th><th class="num">Charges ₹</th><th>Status</th></tr></thead><tbody id="orders"><tr><td colspan="8" class="small">No virtual orders.</td></tr></tbody></table></div></div>
<div class="card"><h2>Paper performance</h2><div id="performance" class="small">No mark-to-market snapshot yet. Click <b>Refresh now</b> after configuring a local access token.</div><h2 style="margin-top:22px">Latest events</h2><div id="events" class="small">—</div></div></section>
<div class="modal" id="modal"><div class="dialog"><h2 id="modal-title">Paper rebalance</h2><p class="small" id="modal-copy"></p><pre id="modal-preview"></pre><div id="modal-confirm-wrap"><label class="small">Type <b>PAPER REBALANCE</b> to create virtual fills only: <input id="rebalance-confirm" autocomplete="off"></label></div><div class="controls"><button id="modal-action">Continue</button><button class="secondary" onclick="closeModal()">Cancel</button></div></div></div>
</main>
<script>
const money = (v) => v == null ? '—' : new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(Number(v));
const stamp = (v) => v ? new Date(v).toLocaleString() : '—';
const escapeHtml = (s) => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let state = null;
async function request(path, payload) { const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload||{})}); const data=await r.json().catch(()=>({error:'Server returned an invalid response'})); if(!r.ok) throw new Error(data.error||'Request failed'); return data; }
function message(text, kind='notice'){document.getElementById('message').innerHTML=text?`<div class="${kind}">${escapeHtml(text)}</div>`:''}
async function load(){try{const r=await fetch('/api/paper/status',{cache:'no-store'}); state=await r.json();render(state)}catch(e){message(e.message,'notice')}}
function render(s){
  const p=s.portfolio||{}, st=s.settings||{}, pnl=Number(p.equity||0)-Number(st.initial_capital||0); const pc=pnl>=0?'pos':'neg';
  document.getElementById('capital').value=st.initial_capital||1000000; document.getElementById('data-mode').value=st.data_mode||'UPSTOX_DATA';
  document.getElementById('watchlist-input').value=(st.watchlist||[]).join(', ');
  const policy=s.risk?.policy||{};document.getElementById('risk-position').value=Math.round((policy.max_position_weight??.15)*100);document.getElementById('risk-gross').value=Math.round((policy.max_gross_exposure??1)*100);document.getElementById('risk-daily-loss').value=Math.round((policy.daily_loss_limit??.03)*100);document.getElementById('risk-drawdown').value=Math.round((policy.max_drawdown??.15)*100);document.getElementById('risk-orders').value=policy.max_orders_per_rebalance??30;
  document.getElementById('metrics').innerHTML=[['Virtual equity','₹'+money(p.equity)],['Total P&L',`${pnl>=0?'+':''}₹${money(pnl)}`,pc],['Available virtual cash','₹'+money(p.cash)],['Quote status',p.quote_status||'—',p.quote_status==='LIVE'?'pos':'']].map(x=>`<div class="card metric"><div class="label">${x[0]}</div><div class="value ${x[2]||''}">${x[1]}</div></div>`).join('');
  const c=s.market_data||{}, health=s.quote_health||{};document.getElementById('connection').innerHTML=`<b>${c.mode||'UPSTOX_DATA'}:</b> ${escapeHtml(c.detail||'unknown')} · monitor is <b>${st.running?'RUNNING':'PAUSED'}</b> · refresh interval ${s.quote_refresh_seconds||30}s · feed <b>${escapeHtml(health.status||'NEVER_REFRESHED')}</b>${health.age_seconds!=null?` (${money(health.age_seconds)}s old)`:''}${health.error?` · ${escapeHtml(health.error)}`:''}`;
  const r=s.risk||{}; document.getElementById('risk-status').innerHTML=`<b class="${r.allowed?'pos':'neg'}">${r.allowed?'Guardrails clear':'Blocked: '+escapeHtml((r.breaches||[]).join(', '))}</b> · daily P&amp;L ₹${money(r.daily_pnl)} · drawdown ${money((r.drawdown_pct||0)*100)}% · gross exposure ${money((r.gross_exposure||0)*100)}%`;
  const approved=Object.entries(s.strategies||{}).filter(([,x])=>x.paper_approved);const selector=document.getElementById('auto-strategy');selector.innerHTML=approved.length?approved.map(([id,x])=>`<option value="${escapeHtml(id)}" ${st.auto_strategy===id?'selected':''}>${escapeHtml(x.label)}</option>`).join(''):'<option value="">No approved strategy</option>';document.getElementById('automation-status').innerHTML=st.auto_paper_enabled?`<b class="pos">ENABLED</b> for ${escapeHtml(st.auto_strategy)} · minimum interval ${money(st.auto_interval_seconds)}s · virtual fills only, still strategy and risk-gated.`:'Disabled by default. Enabling requires an approved strategy, explicit confirmation, NSE hours, and the normal risk checks.';
  const positions=s.positions||[];document.getElementById('positions').innerHTML=positions.length?positions.map(x=>`<tr><td><b>${escapeHtml(x.symbol)}</b></td><td class="num">${money(x.quantity)}</td><td class="num">${money(x.average_entry_cost)}</td><td class="num">${money(x.last_price)}</td><td class="num">${money(x.market_value)}</td><td class="num ${Number(x.unrealized_pnl)>=0?'pos':'neg'}">${x.unrealized_pnl==null?'—':(Number(x.unrealized_pnl)>=0?'+':'')+money(x.unrealized_pnl)}</td><td>${stamp(x.quote_timestamp)}</td></tr>`).join(''):'<tr><td colspan="7" class="small">No virtual positions. Monitoring real data does not spend or allocate virtual capital.</td></tr>';
  const quotes=s.watchlist_quotes||[];document.getElementById('watchlist').innerHTML=quotes.length?quotes.map(x=>`<tr><td><b>${escapeHtml(x.symbol)}</b></td><td class="num">${money(x.last_price)}</td><td class="num">${money(x.bid_price)}</td><td class="num">${money(x.ask_price)}</td><td class="num">${money(x.volume)}</td><td>${stamp(x.source_timestamp)}</td></tr>`).join(''):'<tr><td colspan="6" class="small">No quote snapshot. Configure an access token locally, then click Refresh now.</td></tr>';
  const orders=s.orders||[];document.getElementById('orders').innerHTML=orders.length?orders.map(x=>`<tr><td>${stamp(x.created_at)}</td><td>${escapeHtml(x.strategy_id)}</td><td><b>${escapeHtml(x.symbol)}</b></td><td>${escapeHtml(x.side)}</td><td class="num">${money(x.quantity)}</td><td class="num">${money(x.fill_price)}</td><td class="num">${money(x.charges)}</td><td>${escapeHtml(x.status)}</td></tr>`).join(''):'<tr><td colspan="8" class="small">No virtual orders have been created.</td></tr>';
  const perf=s.performance||{}, bench=s.benchmark||{}, strategyPerf=s.strategy_performance||[];document.getElementById('performance').innerHTML=`<b>Realised:</b> ₹${money(p.realized_pnl)} &nbsp; <b>Unrealised:</b> ₹${money(p.unrealized_pnl)}<br><b>Return:</b> ${money(perf.return_pct)}% · <b>Max drawdown:</b> ${money(perf.max_drawdown_pct)}% · <b>${escapeHtml(bench.symbol||'NIFTY_50')}:</b> ${bench.return_pct==null?'awaiting baseline':money(bench.return_pct)+'%'}<br><b>Strategy attribution:</b> ${strategyPerf.map(x=>`${escapeHtml(x.strategy_id)} ${escapeHtml(x.profitability)}${x.net_pnl==null?'':' ₹'+money(x.net_pnl)}`).join(' · ')||'No strategy trades'}<br><span class="small">Virtual equity is marked from persisted Upstox quote snapshots. Missing/stale quotes are explicitly surfaced rather than invented; mixed-strategy P&amp;L is never guessed.</span>`;
  const strategies=s.strategies||{}; document.getElementById('strategies').innerHTML=Object.entries(strategies).map(([id,x])=>`<div class="strategy"><div><strong>${escapeHtml(x.label)}</strong> <span class="tag ${x.paper_approved?'paper':'warn'}">${escapeHtml(x.status)}</span><div class="small">${escapeHtml(x.reason||'')}</div></div>${x.paper_approved?`<button onclick="previewRebalance('${escapeHtml(id)}')">Preview paper rebalance</button>`:'<span class="small">Research gate pending</span>'}</div>`).join('')||'<span class="small">No strategy registry found.</span>';
  const events=s.events||[];document.getElementById('events').innerHTML=events.length?events.slice(0,6).map(x=>`<div>• ${stamp(x.created_at)} — <b>${escapeHtml(x.event_type)}</b></div>`).join(''):'No events yet.';
}
async function configureAccount(){try{await request('/api/paper/configure',{capital:Number(document.getElementById('capital').value),data_mode:document.getElementById('data-mode').value});message('Paper configuration saved. No broker account was changed.','banner');load()}catch(e){message(e.message)}}
async function startMonitor(){try{await request('/api/paper/start');message('Paper monitor started. It records read-only quote snapshots only.','banner');await refreshQuotes()}catch(e){message(e.message)}}
async function pauseMonitor(){try{await request('/api/paper/pause');message('Paper monitor paused. Existing virtual positions remain marked by the last known quote.','banner');load()}catch(e){message(e.message)}}
async function refreshQuotes(){try{const out=await request('/api/paper/refresh'); if(out.quote_error) message(out.quote_error); else message('Quote snapshot refreshed.','banner');load()}catch(e){message(e.message)}}
async function resetPaper(){const text=prompt('This deletes only the local virtual ledger. Type RESET PAPER to continue:'); if(text!=='RESET PAPER') return; try{await request('/api/paper/reset',{confirmation:text,capital:Number(document.getElementById('capital').value)});message('Local virtual account reset. No broker order was sent.','banner');load()}catch(e){message(e.message)}}
async function saveWatchlist(){try{const symbols=document.getElementById('watchlist-input').value.split(',').map(x=>x.trim()).filter(Boolean);await request('/api/paper/watchlist',{symbols});message('Verified watchlist saved locally.','banner');load()}catch(e){message(e.message)}}
async function saveRiskPolicy(){try{const policy={max_position_weight:Number(document.getElementById('risk-position').value)/100,max_gross_exposure:Number(document.getElementById('risk-gross').value)/100,daily_loss_limit:Number(document.getElementById('risk-daily-loss').value)/100,max_drawdown:Number(document.getElementById('risk-drawdown').value)/100,max_orders_per_rebalance:Number(document.getElementById('risk-orders').value)};await request('/api/paper/risk-policy',{policy});message('Paper-only risk guardrails saved.','banner');load()}catch(e){message(e.message)}}
async function runAudit(){try{const r=await fetch('/api/paper/audit',{cache:'no-store'});const out=await r.json();if(!r.ok)throw new Error(out.error||'Audit failed');document.getElementById('audit-status').innerHTML=out.passed?`<b class="pos">PASS</b> · ${out.filled_order_count} virtual fills reconciled; cash difference ₹${money(out.cash_difference)}.`:`<b class="neg">FAIL</b> · cash difference ₹${money(out.cash_difference)}; inspect CSV exports.`}catch(e){document.getElementById('audit-status').textContent=e.message}}
async function setAutomation(enabled){try{let confirmation='';if(enabled){confirmation=prompt('Type ENABLE AUTO PAPER to activate paper-only automation for an approved strategy:')||'';if(confirmation!=='ENABLE AUTO PAPER')return}await request('/api/paper/automation',{enabled,strategy_id:document.getElementById('auto-strategy').value,confirmation});message(enabled?'Automatic virtual-paper mode enabled. It cannot submit broker orders.':'Automatic virtual-paper mode disabled.','banner');load()}catch(e){message(e.message)}}
function closeModal(){document.getElementById('modal').classList.remove('open')}
async function previewRebalance(id){try{const out=await request('/api/paper/preview',{strategy_id:id});document.getElementById('modal-title').textContent='Preview virtual rebalance — '+id;document.getElementById('modal-copy').textContent=out.ready?'These fills would be priced from current bid/ask quotes and include configured Indian cash-equity cost assumptions.':'Not ready: '+(out.reason||'quotes unavailable');document.getElementById('modal-preview').textContent=JSON.stringify(out.orders||[],null,2);document.getElementById('modal-confirm-wrap').style.display=out.ready?'block':'none';const b=document.getElementById('modal-action');b.textContent=out.ready?'Execute virtual fills':'Close';b.onclick=out.ready?()=>executeRebalance(id):closeModal;document.getElementById('modal').classList.add('open')}catch(e){message(e.message)}}
async function executeRebalance(id){try{const c=document.getElementById('rebalance-confirm').value;const out=await request('/api/paper/rebalance',{strategy_id:id,confirmation:c});closeModal();message(`Virtual rebalance completed: ${(out.results||[]).filter(x=>x.status==='FILLED').length} local paper fills. No broker order was sent.`,'banner');load()}catch(e){message(e.message)}}
load(); window.setInterval(()=>{if(state?.settings?.running) refreshQuotes()},30000);
</script></body></html>"""
