"""Generate COVERAGE.md from committed data — single source of truth for
what's in the repo and how fresh it is. No hand-typed numbers.

Run: python -m tools.build_coverage
Emits: COVERAGE.md at repo root.

All figures are re-derived from the committed CSVs + registry on every run,
so the doc can't drift from the data the way hand-maintained prose does.
"""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "index_history" / "data" / "index_registry.json"
INDEX_CSV = ROOT / "index_history" / "data" / "index_membership_history.csv"
FNO_CSV = ROOT / "fno_history" / "data" / "fno_membership_history.csv"
SHP_FLAT = ROOT / "shareholding_history" / "data" / "parsed" / "_flat.csv"
VAL_REPORT = ROOT / "index_history" / "docs" / "validation_report.md"
OUT = ROOT / "COVERAGE.md"
README = ROOT / "README.md"


def _index_stats() -> tuple[dict, str]:
    """Per-index: current member count + (first, last) valid_from. Returns
    ({index_name: {...}}, data_through) where data_through = max valid_from."""
    stats: dict[str, dict] = {}
    data_through = ""
    with INDEX_CSV.open() as f:
        for r in csv.DictReader(f):
            name = r["index_name"]
            vf = r.get("valid_from") or ""
            d = stats.setdefault(name, {"current": 0, "first": vf, "last": vf})
            if vf:
                if not d["first"] or vf < d["first"]:
                    d["first"] = vf
                if vf > d["last"]:
                    d["last"] = vf
                if vf > data_through:
                    data_through = vf
            if not (r.get("valid_to") or ""):
                d["current"] += 1
    return stats, data_through


def _csv_freshness(path: Path) -> tuple[int, int, str]:
    """(rows, open_intervals, max_valid_from) for an interval CSV."""
    rows = openn = 0
    mx = ""
    with path.open() as f:
        for r in csv.DictReader(f):
            rows += 1
            vf = r.get("valid_from") or ""
            if vf > mx:
                mx = vf
            if not (r.get("valid_to") or ""):
                openn += 1
    return rows, openn, mx


def _shp_freshness() -> tuple[int, str]:
    """(distinct tickers, max period) for shareholding _flat.csv."""
    ticks = set()
    mx = ""
    with SHP_FLAT.open() as f:
        for r in csv.DictReader(f):
            ticks.add(r["ticker"])
            p = r.get("period") or ""
            if p > mx:
                mx = p
    return len(ticks), mx


def _last_validation() -> str:
    if not VAL_REPORT.exists():
        return "n/a"
    m = re.search(r"Validation Report\s*[—-]\s*(\S+)", VAL_REPORT.read_text())
    return m.group(1) if m else "n/a"


def main():
    reg = {i["canonical_name"]: i for i in json.loads(REGISTRY.read_text())["indices"]}
    stats, idx_through = _index_stats()
    fno_rows, fno_open, fno_through = _csv_freshness(FNO_CSV)
    shp_ticks, shp_through = _shp_freshness()

    fam_order = {"broad": 0, "sector": 1, "strategy": 2, "thematic": 3}
    rows = sorted(
        reg.values(),
        key=lambda i: (fam_order.get(i["family"], 9), i["canonical_name"]),
    )

    lines = []
    lines.append("# Coverage")
    lines.append("")
    lines.append("> Generated by `python -m tools.build_coverage` — do not hand-edit.")
    lines.append("")
    lines.append("| Dataset | Freshness | Shipped in repo |")
    lines.append("|---|---|---|")
    lines.append(f"| Index membership | data through **{idx_through}** | yes — `index_history/data/index_membership_history.csv` |")
    lines.append(f"| F&O membership | data through **{fno_through}** | yes — `fno_history/data/fno_membership_history.csv` |")
    lines.append(f"| Shareholding (PIT) | data through **{shp_through}** ({shp_ticks} symbols) | yes — `shareholding_history/data/parsed/_flat.csv` |")
    lines.append(f"| EOD daily OHLC | rebuilt locally (2020-01-01 → today) | **no** — run `nse_eod` fetch/build |")
    lines.append("")
    lines.append(f"- Last validation run: **{_last_validation()}** "
                 f"(`index_history/docs/validation_report.md`)")
    lines.append(f"- F&O: {fno_rows} intervals, {fno_open} currently in segment.")
    lines.append("")
    lines.append("## Indices (42)")
    lines.append("")
    lines.append("`current` = symbols with an open interval today. `target` from the "
                 "registry (blank for sector/thematic indices NSE doesn't fix-size — "
                 "no cardinality guarantee). `first`/`last` = earliest / most recent "
                 "`valid_from` in the data for that index.")
    lines.append("")
    lines.append("| id | index | family | target | current | first | last |")
    lines.append("|---|---|---|--:|--:|---|---|")
    for i in rows:
        name = i["canonical_name"]
        s = stats.get(name, {"current": 0, "first": "—", "last": "—"})
        tgt = i.get("target_size")
        tgt_s = str(tgt) if tgt else "—"
        flag = " ⚠️" if tgt and tgt != s["current"] else ""
        lines.append(
            f"| {i['id']} | {name} | {i['family']} | {tgt_s} | "
            f"{s['current']}{flag} | {s['first']} | {s['last']} |"
        )
    lines.append("")
    lines.append("⚠️ = current member count differs from registry target "
                 "(e.g. Nifty 500 ships 499 — one constituent absent from NSE's "
                 "current published list). See README → Coverage and known gaps.")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"→ {OUT}  ({len(rows)} indices, index data through {idx_through})")

    # Refresh the auto-generated freshness block in README between the markers.
    if README.exists():
        block = (
            f"**Data freshness** (auto-generated → [`COVERAGE.md`](COVERAGE.md)): "
            f"index membership through **{idx_through}** · "
            f"F&O through **{fno_through}** · "
            f"shareholding through **{shp_through}** · "
            f"last validated **{_last_validation()[:10]}**."
        )
        text = README.read_text()
        new = re.sub(
            r"(<!-- COVERAGE:START[^\n]*-->).*?(<!-- COVERAGE:END -->)",
            lambda m: m.group(1) + "\n" + block + "\n" + m.group(2),
            text,
            flags=re.DOTALL,
        )
        if new != text:
            README.write_text(new)
            print(f"→ {README} freshness block updated")


if __name__ == "__main__":
    main()
